import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { DatabaseSync } from 'node:sqlite';
import { fileURLToPath } from 'node:url';

const __dirname=path.dirname(fileURLToPath(import.meta.url));
const publicDir=__dirname;
const db=new DatabaseSync(path.join(__dirname,'fixgo.sqlite'));

db.exec(`PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,name TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'customer',created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS vehicles(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,year INTEGER,make TEXT,model TEXT,trim TEXT,engine TEXT,fuel TEXT,transmission TEXT,vin TEXT,is_default INTEGER DEFAULT 0,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS products(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,brand TEXT,sku TEXT UNIQUE,part_number TEXT,category TEXT,price REAL,old_price REAL,stock INTEGER,rating REAL,reviews INTEGER,warranty TEXT,quality TEXT,fitment TEXT,image TEXT,description TEXT);
CREATE TABLE IF NOT EXISTS fitments(id INTEGER PRIMARY KEY AUTOINCREMENT,product_id INTEGER,year INTEGER,make TEXT,model TEXT,trim TEXT,engine TEXT,FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS cart_items(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,product_id INTEGER,quantity INTEGER,UNIQUE(user_id,product_id),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(product_id) REFERENCES products(id));
CREATE TABLE IF NOT EXISTS wishlist_items(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,product_id INTEGER,UNIQUE(user_id,product_id),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(product_id) REFERENCES products(id));
CREATE TABLE IF NOT EXISTS orders(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,status TEXT,total REAL,payment_status TEXT DEFAULT 'demo_pending',created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS order_items(id INTEGER PRIMARY KEY AUTOINCREMENT,order_id INTEGER,product_id INTEGER,quantity INTEGER,unit_price REAL,FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS services(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,category TEXT,price_min REAL,price_max REAL,description TEXT);
CREATE TABLE IF NOT EXISTS bookings(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,vehicle_id INTEGER,service_id INTEGER,provider TEXT,date TEXT,time TEXT,status TEXT DEFAULT 'Confirmed',plan TEXT,covered INTEGER DEFAULT 0,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS plans(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,monthly REAL,annual REAL,benefits_json TEXT,recommended INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS subscriptions(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,plan_id INTEGER,billing_cycle TEXT,status TEXT,started_at TEXT,renewal_at TEXT,usage_json TEXT DEFAULT '{}',FOREIGN KEY(user_id) REFERENCES users(id),FOREIGN KEY(plan_id) REFERENCES plans(id));
CREATE TABLE IF NOT EXISTS notifications(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,title TEXT,body TEXT,read INTEGER DEFAULT 0,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS support_tickets(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,subject TEXT,message TEXT,status TEXT DEFAULT 'Open',created_at TEXT DEFAULT CURRENT_TIMESTAMP);
`);

const seedCount=db.prepare('SELECT COUNT(*) c FROM products').get().c;
if(!seedCount){
 const products=[
 ['Brembo Front Brake Pads','Brembo','BR-2019-COR','P06044','Brakes',69.99,89.99,18,4.8,126,'2 years','Genuine','2019 Toyota Corolla','https://images.unsplash.com/photo-1615906655593-ad0386982a0f?auto=format&fit=crop&w=900&q=85','Low-dust front brake pads designed for confident stopping.'],
 ['Bosch Premium Oil Filter','Bosch','OF-17-22-COR','0986AF','Filters',18.49,24.99,42,4.7,89,'1 year','OEM','Toyota Corolla 2017–2022','https://images.unsplash.com/photo-1625047509248-ec889cbff17f?auto=format&fit=crop&w=900&q=85','Premium filtration for routine engine maintenance.'],
 ['Denso Iridium Spark Plugs','Denso','SP-IR-01','IK20TT','Engine',42.99,55,31,4.9,214,'1 year','OE','Toyota • Honda • Lexus','https://images.unsplash.com/photo-1635784063384-4b3f0e5b8f30?auto=format&fit=crop&w=900&q=85','Long-life iridium spark plugs with reliable ignition.'],
 ['Bosch Cabin Air Filter','Bosch','CAF-COR-17','0986AF','Filters',27.99,34.99,27,4.8,72,'1 year','OEM','Toyota Corolla 2017–2022','https://images.unsplash.com/photo-1487754180451-c456f719a1fc?auto=format&fit=crop&w=900&q=85','Helps keep cabin air clean and comfortable.'],
 ['Valeo Alternator','Valeo','ALT-FOCUS-16','TG15C','Electrical',189.99,229.99,8,4.6,54,'2 years','Aftermarket','Ford Focus 2016–2020','https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&w=900&q=85','Reliable charging-system replacement.'],
 ['Michelin Primacy Tire','Michelin','TIRE-PRIM-17','PRIMACY4','Tires',159.99,179.99,20,4.8,310,'3 years','Genuine','Multiple vehicles','https://images.unsplash.com/photo-1553440569-bcc63803a83d?auto=format&fit=crop&w=900&q=85','Premium touring tire with balanced comfort and wet grip.'],
 ['Gates Serpentine Belt','Gates','BELT-COR-18','K060780','Belts',31.99,39.99,24,4.7,103,'1 year','OE','Toyota Corolla 2017–2021','https://images.unsplash.com/photo-1504222490345-c075b6008014?auto=format&fit=crop&w=900&q=85','Durable replacement belt for accessory drive systems.'],
 ['Yuasa AGM Battery','Yuasa','BAT-AGM-01','YBX9012','Batteries',149.99,169.99,12,4.8,188,'3 years','Genuine','Multiple vehicles','https://images.unsplash.com/photo-1609521263047-f8f205293f24?auto=format&fit=crop&w=900&q=85','High-performance AGM starting battery.']
 ];
 const ins=db.prepare('INSERT INTO products(name,brand,sku,part_number,category,price,old_price,stock,rating,reviews,warranty,quality,fitment,image,description) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)');
 for(const p of products) ins.run(...p);
 const fit=db.prepare('INSERT INTO fitments(product_id,year,make,model,trim,engine) VALUES(?,?,?,?,?,?)');
 for(const id of [1,2,3,4,7]) fit.run(id,2019,'Toyota','Corolla','LE','1.8L Petrol');
 fit.run(5,2018,'Ford','Focus','SE','2.0L Petrol');
 const svc=db.prepare('INSERT INTO services(name,category,price_min,price_max,description) VALUES(?,?,?,?,?)');
 [['Oil Change','Oil',35,55,'Conventional oil and filter service'],['Synthetic Oil','Oil',50,75,'Full synthetic oil service'],['Tire Rotation','Tires',15,20,'Rotate and inspect all four tires'],['Tire Installation','Tires',15,25,'Mount and install one tire'],['Wheel Balancing','Tires',10,15,'Balance one wheel'],['Battery Installation','Battery',15,25,'Install and test replacement battery'],['Basic Inspection','Inspection',20,30,'General vehicle health inspection'],['Brake Inspection','Brakes',0,0,'Visual brake system inspection'],['Air Filter Installation','Filters',15,20,'Install replacement air filter'],['Brake Pad Installation','Brakes',60,90,'Install front or rear brake pads per axle']].forEach(x=>svc.run(...x));
 const plan=db.prepare('INSERT INTO plans(name,monthly,annual,benefits_json,recommended) VALUES(?,?,?,?,?)');
 plan.run('Basic',7.99,79,JSON.stringify(['Maintenance reminders','Digital maintenance history','Vehicle health checklist','5% off maintenance','5% off installation']),0);
 plan.run('Care',19.99,199,JSON.stringify(['Everything in Basic','1 oil change / year','2 tire rotations / year','Basic vehicle inspection','Battery + brake inspection','10% off maintenance & parts','Priority booking']),1);
 plan.run('Complete',34.99,349,JSON.stringify(['Everything in Care','2 oil changes / year','4 tire rotations / year','2 full vehicle inspections','Battery, brake & fluid checks','15% off parts & installation','Priority appointments']),0);
}

function hash(p,s=crypto.randomBytes(16).toString('hex')){return `${s}:${crypto.scryptSync(p,s,64).toString('hex')}`}
function verify(p,h){const [s,x]=h.split(':');return crypto.timingSafeEqual(crypto.scryptSync(p,s,64),Buffer.from(x,'hex'))}
function token(user){const payload=Buffer.from(JSON.stringify({id:user.id,email:user.email,role:user.role,exp:Date.now()+86400000})).toString('base64url');const sig=crypto.createHmac('sha256',process.env.AUTH_SECRET||'fixgo-development-secret').update(payload).digest('base64url');return payload+'.'+sig}
function auth(req){const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))return null;try{const [p,s]=h.slice(7).split('.');const good=crypto.timingSafeEqual(Buffer.from(s),Buffer.from(crypto.createHmac('sha256',process.env.AUTH_SECRET||'fixgo-development-secret').update(p).digest('base64url')));const u=JSON.parse(Buffer.from(p,'base64url'));return good&&u.exp>Date.now()?u:null}catch{return null}}
function body(req){return new Promise((resolve,reject)=>{let d='';req.on('data',c=>{d+=c;if(d.length>1e6)req.destroy()});req.on('end',()=>{try{resolve(d?JSON.parse(d):{})}catch{reject(new Error('Invalid JSON'))}})})}
function send(res,status,data){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','Access-Control-Allow-Origin':'*'});res.end(JSON.stringify(data))}
function q(sql,args=[]){return db.prepare(sql).all(...args)}
function one(sql,args=[]){return db.prepare(sql).get(...args)}
function run(sql,args=[]){return db.prepare(sql).run(...args)}

async function api(req,res){
 const url=new URL(req.url,'http://localhost'); const p=url.pathname;
 if(req.method==='OPTIONS'){res.writeHead(204,{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type, Authorization','Access-Control-Allow-Methods':'GET,POST,PATCH,DELETE,OPTIONS'});return res.end()}
 try{
  if(p==='/api/health') return send(res,200,{ok:true,database:'sqlite',mode:process.env.NODE_ENV==='production'?'production':'development'});
  if(p==='/api/auth/register'&&req.method==='POST'){const b=await body(req);if(!b.email||!b.password||!b.name||b.password.length<8)return send(res,400,{error:'Name, valid email and password (8+ chars) are required'});try{const r=run('INSERT INTO users(email,password_hash,name) VALUES(?,?,?)',[b.email.toLowerCase(),hash(b.password),b.name]);const u=one('SELECT id,email,name,role FROM users WHERE id=?',[r.lastInsertRowid]);return send(res,201,{user:u,token:token(u)})}catch{return send(res,409,{error:'An account with that email already exists'})}}
  if(p==='/api/auth/login'&&req.method==='POST'){const b=await body(req),u=one('SELECT * FROM users WHERE email=?',[String(b.email||'').toLowerCase()]);if(!u||!verify(b.password||'',u.password_hash))return send(res,401,{error:'Invalid email or password'});return send(res,200,{user:{id:u.id,email:u.email,name:u.name,role:u.role},token:token(u)})}
  if(p==='/api/products'&&req.method==='GET'){const vehicle=url.searchParams.get('vehicle')||'',category=url.searchParams.get('category')||'',brand=url.searchParams.get('brand')||'',sort=url.searchParams.get('sort')||'recommended',search=url.searchParams.get('search')||'';let sql='SELECT * FROM products WHERE 1=1',args=[];if(search){sql+=' AND (name LIKE ? OR brand LIKE ? OR sku LIKE ? OR part_number LIKE ?)';const s='%'+search+'%';args.push(s,s,s,s)}if(category){sql+=' AND category=?';args.push(category)}if(brand){sql+=' AND brand=?';args.push(brand)}const order={low:'price ASC',high:'price DESC',rating:'rating DESC',newest:'id DESC',discount:'(old_price-price)/old_price DESC',popular:'reviews DESC',recommended:'rating DESC, reviews DESC'}[sort]||'rating DESC';sql+=' ORDER BY '+order+' LIMIT 100';let items=q(sql,args);if(vehicle)items=items.map(x=>({...x,compatible:x.fitment?.toLowerCase().includes(vehicle.toLowerCase())||vehicle.toLowerCase().includes('2019 toyota corolla')&&[1,2,3,4,7].includes(x.id)}));return send(res,200,{items})}
  if(p.match(/^\/api\/products\/\d+$/)&&req.method==='GET'){const id=Number(p.split('/').pop()),x=one('SELECT * FROM products WHERE id=?',[id]);if(!x)return send(res,404,{error:'Product not found'});const f=q('SELECT * FROM fitments WHERE product_id=?',[id]);return send(res,200,{...x,fitments:f})}
  const u=auth(req);
  if(p==='/api/garage'&&req.method==='GET'){if(!u)return send(res,401,{error:'Login required'});return send(res,200,{vehicles:q('SELECT * FROM vehicles WHERE user_id=? ORDER BY is_default DESC,id DESC',[u.id])})}
  if(p==='/api/garage'&&req.method==='POST'){if(!u)return send(res,401,{error:'Login required'});const b=await body(req);if(b.is_default)run('UPDATE vehicles SET is_default=0 WHERE user_id=?',[u.id]);const r=run('INSERT INTO vehicles(user_id,year,make,model,trim,engine,fuel,transmission,vin,is_default) VALUES(?,?,?,?,?,?,?,?,?,?)',[u.id,b.year,b.make,b.model,b.trim,b.engine,b.fuel,b.transmission,b.vin,b.is_default?1:0]);return send(res,201,one('SELECT * FROM vehicles WHERE id=?',[r.lastInsertRowid]))}
  if(p.startsWith('/api/garage/')&&req.method==='DELETE'){if(!u)return send(res,401,{error:'Login required'});run('DELETE FROM vehicles WHERE id=? AND user_id=?',[Number(p.split('/').pop()),u.id]);return send(res,200,{ok:true})}
  if(p==='/api/cart'&&req.method==='GET'){if(!u)return send(res,401,{error:'Login required'});const items=q('SELECT c.quantity,p.* FROM cart_items c JOIN products p ON p.id=c.product_id WHERE c.user_id=?',[u.id]);return send(res,200,{items,total:items.reduce((a,x)=>a+x.quantity*x.price,0)})}
  if(p==='/api/cart'&&req.method==='POST'){if(!u)return send(res,401,{error:'Login required'});const b=await body(req);run('INSERT INTO cart_items(user_id,product_id,quantity) VALUES(?,?,?) ON CONFLICT(user_id,product_id) DO UPDATE SET quantity=quantity+excluded.quantity',[u.id,b.product_id,Math.max(1,Number(b.quantity||1))]);return send(res,200,{ok:true})}
  if(p==='/api/cart'&&req.method==='DELETE'){if(!u)return send(res,401,{error:'Login required'});const b=await body(req);run('DELETE FROM cart_items WHERE user_id=? AND product_id=?',[u.id,b.product_id]);return send(res,200,{ok:true})}
  if(p==='/api/wishlist'&&req.method==='GET'){if(!u)return send(res,401,{error:'Login required'});return send(res,200,{items:q('SELECT p.* FROM wishlist_items w JOIN products p ON p.id=w.product_id WHERE w.user_id=?',[u.id])})}
  if(p==='/api/wishlist'&&req.method==='POST'){if(!u)return send(res,401,{error:'Login required'});const b=await body(req);run('INSERT OR IGNORE INTO wishlist_items(user_id,product_id) VALUES(?,?)',[u.id,b.product_id]);return send(res,200,{ok:true})}
  if(p==='/api/wishlist'&&req.method==='DELETE'){if(!u)return send(res,401,{error:'Login required'});const b=await body(req);run('DELETE FROM wishlist_items WHERE user_id=? AND product_id=?',[u.id,b.product_id]);return send(res,200,{ok:true})}
  if(p==='/api/checkout'&&req.method==='POST'){if(!u)return send(res,401,{error:'Login required'});const items=q('SELECT c.quantity,p.id,p.price FROM cart_items c JOIN products p ON p.id=c.product_id WHERE c.user_id=?',[u.id]);if(!items.length)return send(res,400,{error:'Cart is empty'});const total=items.reduce((a,x)=>a+x.quantity*x.price,0);const r=run('INSERT INTO orders(user_id,status,total) VALUES(?,?,?)',[u.id,'Confirmed',total]);const ins=db.prepare('INSERT INTO order_items(order_id,product_id,quantity,unit_price) VALUES(?,?,?,?)');for(const x of items)ins.run(r.lastInsertRowid,x.id,x.quantity,x.price);run('DELETE FROM cart_items WHERE user_id=?',[u.id]);run('INSERT INTO notifications(user_id,title,body) VALUES(?,?,?)',[u.id,'Order confirmed',`Order #${r.lastInsertRowid} has been confirmed in demo mode.`]);return send(res,201,{order:one('SELECT * FROM orders WHERE id=?',[r.lastInsertRowid]),mode:'development'})}
  if(p==='/api/orders'&&req.method==='GET'){if(!u)return send(res,401,{error:'Login required'});return send(res,200,{orders:q('SELECT * FROM orders WHERE user_id=? ORDER BY id DESC',[u.id])})}
  if(p==='/api/services'&&req.method==='GET')return send(res,200,{services:q('SELECT * FROM services ORDER BY category,name'),plans:q('SELECT * FROM plans') .map(x=>({...x,benefits:JSON.parse(x.benefits_json)}))});
  if(p==='/api/bookings'&&req.method==='POST'){if(!u)return send(res,401,{error:'Login required'});const b=await body(req);const r=run('INSERT INTO bookings(user_id,vehicle_id,service_id,provider,date,time,plan,covered) VALUES(?,?,?,?,?,?,?,?)',[u.id,b.vehicle_id,b.service_id,b.provider||'Fix&Go Central Garage',b.date,b.time,b.plan||'Pay-As-You-Go',b.covered?1:0]);run('INSERT INTO notifications(user_id,title,body) VALUES(?,?,?)',[u.id,'Booking confirmed',`Your ${b.service_name||'service'} is booked for ${b.date} at ${b.time}.`]);return send(res,201,one('SELECT * FROM bookings WHERE id=?',[r.lastInsertRowid]))}
  if(p==='/api/bookings'&&req.method==='GET'){if(!u)return send(res,401,{error:'Login required'});return send(res,200,{bookings:q('SELECT b.*,s.name service_name,s.price_min,s.price_max FROM bookings b JOIN services s ON s.id=b.service_id WHERE b.user_id=? ORDER BY b.date DESC,b.time DESC',[u.id])})}
  if(p==='/api/subscription'&&req.method==='GET'){if(!u)return send(res,401,{error:'Login required'});const s=one('SELECT s.*,p.name plan_name,p.monthly,p.annual,p.benefits_json FROM subscriptions s JOIN plans p ON p.id=s.plan_id WHERE s.user_id=? AND s.status="Active" ORDER BY s.id DESC LIMIT 1',[u.id]);return send(res,200,{subscription:s?{...s,benefits:JSON.parse(s.benefits_json),usage:JSON.parse(s.usage_json)}:null})}
  if(p==='/api/subscription'&&req.method==='POST'){if(!u)return send(res,401,{error:'Login required'});const b=await body(req);const plan=one('SELECT * FROM plans WHERE id=?',[b.plan_id]);if(!plan)return send(res,404,{error:'Plan not found'});run('UPDATE subscriptions SET status="Cancelled" WHERE user_id=? AND status="Active"',[u.id]);const start=new Date(),renewal=new Date(start);renewal.setMonth(renewal.getMonth()+1);const r=run('INSERT INTO subscriptions(user_id,plan_id,billing_cycle,status,started_at,renewal_at) VALUES(?,?,?,?,?,?)',[u.id,plan.id,b.billing_cycle||'monthly','Active',start.toISOString(),renewal.toISOString()]);return send(res,201,{subscription:one('SELECT s.*,p.name plan_name,p.monthly,p.annual,p.benefits_json FROM subscriptions s JOIN plans p ON p.id=s.plan_id WHERE s.id=?',[r.lastInsertRowid])})}
  if(p==='/api/ai'&&req.method==='POST'){const b=await body(req);const v=b.vehicle||'your selected vehicle';const text=(b.message||'').toLowerCase();let reply=`For ${v}, I can help narrow this down using Fix&Go's vehicle-aware catalog. `;if(text.includes('oil'))reply+='For an oil service, check the correct oil grade and filter for the engine before booking. I can also show compatible oil filters.';else if(text.includes('brake'))reply+='Brake symptoms should be checked promptly. If you hear grinding, feel vibration, or notice reduced braking, book a brake inspection with a professional.';else if(text.includes('battery'))reply+='If starting is slow or electrical systems are weak, a battery health test can help distinguish a weak battery from a charging-system issue.';else reply+='Tell me the symptom, warning light, part, or maintenance task and I’ll guide you to relevant Fix&Go products or services. This is general guidance, not a guaranteed diagnosis.';return send(res,200,{reply,development_adapter:true})}
  if(p==='/api/support'&&req.method==='POST'){if(!u)return send(res,401,{error:'Login required'});const b=await body(req);const r=run('INSERT INTO support_tickets(user_id,subject,message) VALUES(?,?,?)',[u.id,b.subject,b.message]);return send(res,201,one('SELECT * FROM support_tickets WHERE id=?',[r.lastInsertRowid]))}
  if(p==='/api/admin'&&req.method==='GET'){if(!u||u.role!=='admin')return send(res,403,{error:'Admin access required'});return send(res,200,{stats:{products:one('SELECT COUNT(*) c FROM products').c,users:one('SELECT COUNT(*) c FROM users').c,orders:one('SELECT COUNT(*) c FROM orders').c,revenue:one('SELECT COALESCE(SUM(total),0) c FROM orders').c,subscriptions:one('SELECT COUNT(*) c FROM subscriptions WHERE status="Active"').c},orders:q('SELECT o.*,u.email FROM orders o JOIN users u ON u.id=o.user_id ORDER BY o.id DESC LIMIT 20')})}
  return send(res,404,{error:'API route not found'});
 }catch(e){console.error(e);return send(res,500,{error:'Server error'})}
}

const server=http.createServer((req,res)=>{if(req.url.startsWith('/api/'))return api(req,res);let file=path.join(publicDir,req.url==='/'?'index.html':req.url.split('?')[0]);if(!file.startsWith(publicDir)||!fs.existsSync(file)||fs.statSync(file).isDirectory())file=path.join(publicDir,'index.html');const ext=path.extname(file);const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.svg':'image/svg+xml'};res.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream'});fs.createReadStream(file).pipe(res)});
server.listen(process.env.PORT||3000,()=>console.log(`Fix&Go running on http://localhost:${process.env.PORT||3000}`));
